### ISSUE TITLE
/api/import and /api/export are 500 Internal Server Error

### ISSUE THREAD

**Issue by foolip** [foolip/ecosystem-infra-rotation#13]
https://ecosystem-infra-rotation.appspot.com/api/wptsync/import
https://ecosystem-infra-rotation.appspot.com/api/wptsync/export

**Comment by foolip** [comment]
Logs say:
```
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/main.py", line 40, in wptsync_export
    return jsonify(wptsync.export_status())
  File "/srv/wptsync.py", line 54, in export_status
    return scrape_buildbot(EXPORT_URL)
  File "/srv/wptsync.py", line 24, in scrape_buildbot
    build = BASE_URL + columns[4].a['href']
TypeError: 'NoneType' object is not subscriptable
```
